name : Build & Deploy solideportal app

on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    name:  Build & Deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 8
          
#      - name: Unit Tests
#        run: mvn -B test --file pom.xml
            
      - name: Configure GitHub Packages for Maven 
        run: mvn --settings .github/workflows/maven-settings.xml clean install 
        env: 
          SOLIDE_TOKEN: ${{ secrets.SOLIDE_TOKEN }}
          
          
#      - name: Build Docker Image
#        uses: docker/build-push-action@v2
#        with: 
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/solideportal:latest
#           
#      - name: Login Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#            
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v2
#        with: 
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/solideportal:latest
#               
           
           
           